---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  #adapter:  mongo
  database: food_picker_development
  username: root
  password: password
  host:     localhost

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgresql
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  <<:       *defaults
  database: food_picker_test

  # repositories:
  #   repo1:
  #     database: sample_development

production:
  <<:       *defaults
  database: food_picker_production

  # repositories:
  #   repo1:
  #     database: sample_development
rake:
  <<:       *defaults
